import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final l10n = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(l10n != null, 'AppLocalizations not found in widget tree');
    return l10n!;
  }

  static const _localizedValues = <String, Map<String, String>>{
    'ar': {
      'appTitle': 'مساعد إكسل الذكي',
      'onboarding1': 'حلّل ملفاتك بسرعة باستخدام الذكاء الاصطناعي',
      'onboarding2': 'أنشئ تقارير ولوحات تحكم تلقائياً',
      'onboarding3': 'اقرأ وصدّر ملفات Excel بصيغ متعددة',
      'next': 'التالي',
      'start': 'ابدأ الآن',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'guest': 'الدخول كضيف',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'home': 'الرئيسية',
      'upload': 'رفع ملف',
      'analyze': 'تحليل',
      'aiPrompt': 'اكتب طلبك للذكاء الاصطناعي',
      'generate': 'تنفيذ الطلب',
      'toggleLanguage': 'تغيير اللغة',
      'workspaceTitle': 'مساحة عمل Excel + AI',
      'noFileSelected': 'لم يتم اختيار ملف بعد',
      'aiOutputPlaceholder': 'سيظهر ناتج الذكاء الاصطناعي هنا...',
      'signinSuccess': 'تم تسجيل الدخول بنجاح',
      'signupSuccess': 'تم إنشاء الحساب بنجاح',
      'guestSuccess': 'تم الدخول كضيف',
      'invalidEmail': 'الرجاء إدخال بريد إلكتروني صحيح',
      'shortPassword': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'requiredField': 'هذا الحقل مطلوب',
      'signOut': 'تسجيل الخروج',
      'authRequired': 'يجب تسجيل الدخول أو اختيار الدخول كضيف أولاً',
      'searchHint': 'مثال: حلل المبيعات الشهرية وأنشئ تقرير PDF',
      'geminiMissing': 'مفتاح Gemini غير مضاف. استخدم --dart-define=GEMINI_API_KEY=...',
      'welcomeBack': 'مرحباً بك',
      'modeGuest': 'وضع الضيف',
      'modeUser': 'مستخدم مسجل',
      'autopilot': 'وضع الطيار الآلي',
      'autopilotDone': 'تم تنفيذ سير الطيار الآلي بنجاح',
      'generatedFilePath': 'مسار الملف الناتج',
      'filePreview': 'معاينة الملف',
      'searchWeb': 'بحث ويب ذكي',
      'searchResults': 'نتائج الويب',
      'searchNoResult': 'لا توجد نتائج بحث حالياً',
      'searchMissing': 'مفاتيح محرك البحث غير مضبوطة. استخدم SEARCH_API_KEY و SEARCH_ENGINE_CX',
      'geminiStatus': 'حالة Gemini',
      'searchStatus': 'حالة البحث',
      'statusReady': 'جاهز',
      'statusMissing': 'غير مضاف',
      'unexpectedError': 'حدث خطأ غير متوقع، حاول مرة أخرى.',
      'emptyPrompt': 'الرجاء كتابة طلب أولاً',
      'copied': 'تم نسخ الناتج',
      'copyOutput': 'نسخ الناتج',
      'clearOutput': 'مسح الناتج',
      'previewPathMissing': 'مسار الملف غير متاح.',
      'previewCsvEmpty': 'ملف CSV فارغ.',
      'previewSpreadsheetSelected': 'تم اختيار ملف جدول بنجاح. يمكن إضافة معاينة تفصيلية لاحقاً.',
      'previewUnsupported': 'صيغة الملف غير مدعومة.',
      'openSheetEditor': 'فتح محرر الجداول',
      'sheetEditor': 'محرر الجداول',
      'editCell': 'تعديل خلية',
      'cellHint': 'اكتب قيمة أو معادلة مثل =SUM(A1:A3) أو =AVG(A1:A3)',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'saveCsv': 'حفظ CSV',
      'saveXlsx': 'حفظ XLSX',
      'savedTo': 'تم الحفظ في',
      'selectedCell': 'الخلية المحددة',
      'value': 'القيمة',
      'resolved': 'الناتج',
      'reportsCenter': 'مركز التقارير',
      'settings': 'الإعدادات',
      'expertReview': 'مراجعة فريق الخبراء',
      'expertReviewIntro': 'تمت مراجعة التطبيق عبر قائمة تحقق تقنية لضمان الجاهزية والجودة.',
      'reviewArchitecture': 'فحص المعمارية وتقسيم الميزات',
      'reviewLocalization': 'فحص الترجمة الكاملة عربي/إنجليزي',
      'reviewExcelFlow': 'فحص تدفق ملفات Excel (رفع/تحرير/تصدير)',
      'reviewAiFlow': 'فحص تكامل Gemini ومحرك البحث',
      'reviewErrorHandling': 'فحص إدارة الأخطاء وحالات التحميل',
      'reviewSecurity': 'فحص أمن المفاتيح عبر dart-define',
      'darkMode': 'الوضع الداكن',
      'animationsEnabled': 'تفعيل الأنيميشن',
      'keysStatus': 'حالة مفاتيح الخدمات',
      'monthlySalesReport': 'تقرير المبيعات الشهرية',
      'expenseBreakdownReport': 'تقرير توزيع المصروفات',
      'forecastReport': 'تقرير التوقعات',
      'templatesCenter': 'مركز القوالب',
      'budgetTemplate': 'قالب الميزانية الشهرية',
      'budgetTemplateDesc': 'قالب جاهز لمتابعة المخطط مقابل الفعلي',
      'invoiceTemplate': 'قالب الفاتورة',
      'invoiceTemplateDesc': 'قالب فاتورة مع مجموع تلقائي',
      'helpCenter': 'مركز المساعدة',
      'faqSheetEdit': 'كيف أعدل الخلايا والصيغ؟',
      'faqFormulas': 'ما هي الصيغ المدعومة حالياً؟ (SUM/AVG/MIN/MAX/مرجع خلية)',
      'faqExport': 'كيف أقوم بتصدير الملفات؟',
      'generateMonthlyReportDesc': 'توليد ملف تقرير مبيعات شهري جاهز للتحرير',
      'resetSettings': 'إعادة تعيين الإعدادات',
      'dashboard': 'لوحة المؤشرات',
      'kpiRevenue': 'نمو الإيرادات',
      'kpiEfficiency': 'كفاءة التشغيل',
      'kpiReports': 'التقارير المنشأة',
      'kpiAutomation': 'مهام الأتمتة',
      'dashboardInsight': 'أداءك ممتاز اليوم، واصل تحسين الأتمتة للتوسع.',
      'automationCenter': 'مركز الأتمتة',
      'autoCleanup': 'تنظيف البيانات التلقائي',
      'autoForecast': 'توقعات تلقائية',
      'autoDistribution': 'توزيع تلقائي للتقارير',
      'scheduledReports': 'تقارير مجدولة',
      'runAllAutomations': 'تشغيل كل الأتمتة',
      'dataCatalog': 'كتالوج البيانات',
      'lastUpdatedToday': 'آخر تحديث: اليوم',
      'apiKeysManager': 'إدارة مفاتيح API',
      'rotateKeys': 'تدوير المفاتيح',
      'billing': 'الفواتير والاشتراك',
      'currentPlan': 'الخطة الحالية',
      'proPlan': 'خطة احترافية',
      'managePlan': 'إدارة الخطة',
      'invoiceHistory': 'سجل الفواتير',
      'paymentMethods': 'طرق الدفع',
      'promoCodes': 'أكواد الخصم',
      'teamWorkspace': 'مساحة الفريق',
      'activeNow': 'نشط الآن',
      'inviteMember': 'دعوة عضو',
      'integrations': 'التكاملات',
      'integrationsHint': 'قم بربط أدواتك لتدفقات عمل أكثر ذكاءً.',
      'activityTimeline': 'الخط الزمني للنشاط',
      'activityUpload': 'تم رفع ملف جديد',
      'activityAiRun': 'تم تشغيل تحليل الذكاء الاصطناعي',
      'activityReport': 'تم إنشاء تقرير جديد',
      'activityShare': 'تمت مشاركة تقرير مع الفريق',
      'backupRestore': 'النسخ الاحتياطي والاستعادة',
      'createBackup': 'إنشاء نسخة احتياطية',
      'restoreBackup': 'استعادة نسخة احتياطية',
      'backupHistory': 'سجل النسخ الاحتياطية',
      'backupHint': 'احتفظ بنسخ آمنة لبياناتك بشكل دوري.',
      'supportTickets': 'تذاكر الدعم',
      'openTicket': 'فتح تذكرة جديدة',
      'myTickets': 'تذاكري',
      'liveChat': 'الدعم المباشر',
      'settingsResetDone': 'تمت إعادة الإعدادات الافتراضية',
      'progressCenter': 'مركز تقدم المستخدم',
      'uploadedFilesCount': 'عدد الملفات المرفوعة',
      'aiRunsCount': 'عدد مرات تشغيل الذكاء الاصطناعي',
      'webSearchRunsCount': 'عدد مرات بحث الويب',
      'autopilotRunsCount': 'عدد مرات الطيار الآلي',
      'progressInsights': 'استمر! تقدمك يتحسن مع كل تحليل جديد.',
      'profile': 'الملف الشخصي',
      'notifications': 'الإشعارات',
      'privacySecurity': 'الخصوصية والأمان',
      'subscriptionStatus': 'حالة الاشتراك',
      'notifInsightReady': 'تم تجهيز رؤى تحليل جديدة.',
      'notifReportGenerated': 'تم إنشاء تقريرك بنجاح.',
      'notifSyncComplete': 'اكتملت مزامنة البيانات السحابية.',
      'notifAiSuggestion': 'يوجد اقتراح ذكي لتحسين الورقة.',
      'today': 'اليوم',
      'twoFactorAuth': 'المصادقة الثنائية',
      'dataEncryption': 'تشفير البيانات',
      'privacyControls': 'عناصر تحكم الخصوصية',
      'appearanceSection': 'المظهر والتجربة',
      'workflowSection': 'سير العمل والإنتاجية',
      'aiSection': 'مساعد الذكاء الاصطناعي',
      'securitySection': 'الخصوصية والأمان',
      'languageSection': 'اللغة والمنطقة',
      'compactMode': 'الوضع المضغوط',
      'haptics': 'اهتزازات اللمس',
      'autoSave': 'حفظ تلقائي',
      'cloudSync': 'مزامنة سحابية',
      'offlineCache': 'تخزين دون اتصال',
      'smartNotifications': 'تنبيهات ذكية',
      'defaultExportFormat': 'صيغة التصدير الافتراضية',
      'formulaHints': 'إرشادات الصيغ الذكية',
      'aiAutofill': 'إكمال تلقائي بالذكاء الاصطناعي',
      'highAccuracyMode': 'وضع الدقة العالية',
      'experimentalFeatures': 'الميزات التجريبية',
      'secureMode': 'الوضع الآمن',
      'batterySaver': 'توفير الطاقة',
      'appLanguage': 'لغة التطبيق',
      'undo': 'تراجع',
      'redo': 'إعادة',
      'formulaSupportTip': 'الصيغ المدعومة: SUM / AVG / MIN / MAX / مرجع خلية (مثال: =A1)',
      'pasteTable': 'لصق جدول',
      'clearSheet': 'مسح الورقة',
      'confirmClearSheet': 'هل أنت متأكد من مسح جميع الخلايا؟',
      'yes': 'نعم',
      'pastedRange': 'تم لصق البيانات في الجدول',
      'fillDown': 'تعبئة للأسفل',
      'sortByColumn': 'فرز العمود',
      'endRowHint': 'رقم الصف النهائي',
      'apply': 'تطبيق',
      'sortState': 'وضع الفرز',
      'ascending': 'تصاعدي',
      'descending': 'تنازلي',
      'columnStats': 'إحصائيات العمود',
      'duplicateRow': 'تكرار الصف',
      'insertRowBelow': 'إدراج صف أسفل',
      'insertColumnRight': 'إدراج عمود يمين',
      'goToCell': 'الانتقال إلى خلية',
      'go': 'انتقال',
      'arithmeticFormulasTip': 'يدعم العمليات الحسابية مثل =A1+B1 و =(A1*2)-3',
      'advancedFormulaTip': 'صيغ متقدمة: COUNT / MEDIAN على النطاقات',
      'conditionalFormulaTip': 'يدعم IF مثل =IF(A2>100,"مرتفع","منخفض")',
      'optimizeSheet': 'تحسين الورقة (حذف الفارغ)',
      'sheetOptimized': 'تم تحسين الورقة',
      'columnDeepStats': 'إحصائيات متقدمة للعمود',
      'sumValue': 'المجموع',
      'medianValue': 'الوسيط',
      'varianceValue': 'التباين',
      'stdevValue': 'الانحراف المعياري',
      'dispersionFormulaTip': 'يدعم STDEV و VAR على النطاقات',
      'rankingFormulaTip': 'يدعم PCTL و RANK للتحليل المتقدم',
      'formulaAssistant': 'مساعد الصيغ',
      'normalizeColumn': 'تطبيع العمود (Z-Score)',
      'normalizedCells': 'الخلايا المطبّعة',
      'outlierDetection': 'كشف القيم الشاذة',
      'outlierRows': 'صفوف القيم الشاذة',
      'noOutliers': 'لا توجد قيم شاذة',
      'outlierTip': 'كشف الشذوذ: IQR + تطبيع Z-Score',
      'trendInsights': 'رؤى الاتجاه',
      'trendSlope': 'ميل الاتجاه',
      'trendIntercept': 'الثابت',
      'samplesUsed': 'العينات المستخدمة',
      'nextForecasts': 'التوقعات القادمة',
      'movingAverage': 'المتوسط المتحرك',
      'windowSizeHint': 'حجم النافذة (مثال 3)',
      'movingAverageApplied': 'تم تطبيق المتوسط المتحرك في العمود',
      'trendTip': 'تحليل اتجاه + توقعات تلقائية',
      'goalSeek': 'تحقيق الهدف',
      'goalSeekHint': 'أدخل الهدف المطلوب لقيمة Y',
      'requiredX': 'قيمة X المطلوبة',
      'whatIfScenario': 'سيناريو ماذا لو',
      'scenarioHint': 'اكتب قيم X مفصولة بفواصل مثل 10,20,30',
      'scenarioTip': 'سيناريوهات هدف/ماذا لو للتنبؤ',
      'insufficientData': 'بيانات غير كافية للتحليل',
      'trimSheet': 'تنظيف الفراغات النهائية',
      'sheetTrimmed': 'تم تنظيف الورقة',
      'formulaAudit': 'تدقيق الصيغ',
      'formulaAuditClean': 'لا توجد أخطاء صيغ مكتشفة',
      'autoExpandPrompt': 'الخلية خارج النطاق. هل تريد توسيع الورقة تلقائياً؟',
      'count': 'العدد',
      'minValue': 'أدنى قيمة',
      'maxValue': 'أعلى قيمة',
      'avgValue': 'المتوسط',
      'ok': 'حسنًا',
      'findInSheet': 'بحث داخل الورقة',
      'replaceInSheet': 'استبدال داخل الورقة',
      'findHint': 'اكتب نص البحث',
      'find': 'بحث',
      'replaceWith': 'استبدال بـ',
      'noMatches': 'لا توجد نتائج مطابقة',
      'matchesFound': 'عدد النتائج',
      'replacedCount': 'عدد الخلايا المستبدلة',
      'deleteRow': 'حذف الصف',
      'deleteColumn': 'حذف العمود',
      'confirmDeleteRow': 'هل تريد حذف الصف المحدد؟',
      'confirmDeleteColumn': 'هل تريد حذف العمود المحدد؟',
    },
    'en': {
      'appTitle': 'Excel AI Assistant',
      'onboarding1': 'Analyze your sheets fast with AI assistance',
      'onboarding2': 'Auto-build reports and smart dashboards',
      'onboarding3': 'Read & export Excel-compatible formats',
      'next': 'Next',
      'start': 'Get Started',
      'login': 'Login',
      'signup': 'Create Account',
      'guest': 'Continue as Guest',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'home': 'Home',
      'upload': 'Upload File',
      'analyze': 'Analyze',
      'aiPrompt': 'Write your AI request',
      'generate': 'Run Request',
      'toggleLanguage': 'Toggle Language',
      'workspaceTitle': 'Excel + AI Workspace',
      'noFileSelected': 'No file selected yet',
      'aiOutputPlaceholder': 'AI output will appear here...',
      'signinSuccess': 'Signed in successfully',
      'signupSuccess': 'Account created successfully',
      'guestSuccess': 'Continued as guest',
      'invalidEmail': 'Please enter a valid email address',
      'shortPassword': 'Password must be at least 6 characters',
      'requiredField': 'This field is required',
      'signOut': 'Sign out',
      'authRequired': 'Please login or continue as guest first',
      'searchHint': 'Example: Analyze monthly sales and create a PDF report',
      'geminiMissing': 'Gemini key is missing. Use --dart-define=GEMINI_API_KEY=...',
      'welcomeBack': 'Welcome back',
      'modeGuest': 'Guest mode',
      'modeUser': 'Signed-in user',
      'autopilot': 'Autopilot',
      'autopilotDone': 'Autopilot workflow completed',
      'generatedFilePath': 'Generated file path',
      'filePreview': 'File preview',
      'searchWeb': 'Smart Web Search',
      'searchResults': 'Web results',
      'searchNoResult': 'No results found right now',
      'searchMissing': 'Search keys are missing. Use SEARCH_API_KEY and SEARCH_ENGINE_CX',
      'geminiStatus': 'Gemini status',
      'searchStatus': 'Search status',
      'statusReady': 'Ready',
      'statusMissing': 'Missing',
      'unexpectedError': 'Unexpected error, please try again.',
      'emptyPrompt': 'Please enter a request first',
      'copied': 'Output copied',
      'copyOutput': 'Copy Output',
      'clearOutput': 'Clear Output',
      'previewPathMissing': 'File path is not available.',
      'previewCsvEmpty': 'CSV file is empty.',
      'previewSpreadsheetSelected': 'Spreadsheet selected successfully. Detailed preview can be added in the next phase.',
      'previewUnsupported': 'Unsupported file format.',
      'openSheetEditor': 'Open Sheet Editor',
      'sheetEditor': 'Sheet Editor',
      'editCell': 'Edit Cell',
      'cellHint': 'Enter a value or formula like =SUM(A1:A3) or =AVG(A1:A3)',
      'cancel': 'Cancel',
      'save': 'Save',
      'saveCsv': 'Save CSV',
      'saveXlsx': 'Save XLSX',
      'savedTo': 'Saved to',
      'selectedCell': 'Selected Cell',
      'value': 'Value',
      'resolved': 'Resolved',
      'reportsCenter': 'Reports Center',
      'settings': 'Settings',
      'expertReview': 'Expert Team Review',
      'expertReviewIntro': 'The app was reviewed using a technical readiness and quality checklist.',
      'reviewArchitecture': 'Checked architecture and feature separation',
      'reviewLocalization': 'Checked full Arabic/English localization',
      'reviewExcelFlow': 'Checked Excel file flow (upload/edit/export)',
      'reviewAiFlow': 'Checked Gemini and web search integrations',
      'reviewErrorHandling': 'Checked error and loading state handling',
      'reviewSecurity': 'Checked key security via dart-define',
      'darkMode': 'Dark Mode',
      'animationsEnabled': 'Enable Animations',
      'keysStatus': 'Service keys status',
      'monthlySalesReport': 'Monthly Sales Report',
      'expenseBreakdownReport': 'Expense Breakdown Report',
      'forecastReport': 'Forecast Report',
      'templatesCenter': 'Templates Center',
      'budgetTemplate': 'Monthly Budget Template',
      'budgetTemplateDesc': 'Ready template to track planned vs actual',
      'invoiceTemplate': 'Invoice Template',
      'invoiceTemplateDesc': 'Invoice template with automatic totals',
      'helpCenter': 'Help Center',
      'faqSheetEdit': 'How do I edit cells and formulas?',
      'faqFormulas': 'Which formulas are currently supported? (SUM/AVG/MIN/MAX/cell reference)',
      'faqExport': 'How can I export files?',
      'generateMonthlyReportDesc': 'Generate an editable monthly sales report file',
      'resetSettings': 'Reset Settings',
      'dashboard': 'Dashboard',
      'kpiRevenue': 'Revenue Growth',
      'kpiEfficiency': 'Operational Efficiency',
      'kpiReports': 'Reports Generated',
      'kpiAutomation': 'Automation Jobs',
      'dashboardInsight': 'Excellent performance today. Keep improving automation for scale.',
      'automationCenter': 'Automation Center',
      'autoCleanup': 'Auto Data Cleanup',
      'autoForecast': 'Auto Forecasting',
      'autoDistribution': 'Auto Report Distribution',
      'scheduledReports': 'Scheduled Reports',
      'runAllAutomations': 'Run All Automations',
      'dataCatalog': 'Data Catalog',
      'lastUpdatedToday': 'Last updated: today',
      'apiKeysManager': 'API Keys Manager',
      'rotateKeys': 'Rotate Keys',
      'billing': 'Billing & Subscription',
      'currentPlan': 'Current Plan',
      'proPlan': 'Pro Plan',
      'managePlan': 'Manage Plan',
      'invoiceHistory': 'Invoice History',
      'paymentMethods': 'Payment Methods',
      'promoCodes': 'Promo Codes',
      'teamWorkspace': 'Team Workspace',
      'activeNow': 'Active now',
      'inviteMember': 'Invite Member',
      'integrations': 'Integrations',
      'integrationsHint': 'Connect your tools for smarter workflows.',
      'activityTimeline': 'Activity Timeline',
      'activityUpload': 'New file uploaded',
      'activityAiRun': 'AI analysis executed',
      'activityReport': 'New report generated',
      'activityShare': 'Report shared with team',
      'backupRestore': 'Backup & Restore',
      'createBackup': 'Create Backup',
      'restoreBackup': 'Restore Backup',
      'backupHistory': 'Backup History',
      'backupHint': 'Keep secure snapshots of your data regularly.',
      'supportTickets': 'Support Tickets',
      'openTicket': 'Open New Ticket',
      'myTickets': 'My Tickets',
      'liveChat': 'Live Chat',
      'settingsResetDone': 'Default settings restored',
      'progressCenter': 'Progress Center',
      'uploadedFilesCount': 'Uploaded Files',
      'aiRunsCount': 'AI Runs',
      'webSearchRunsCount': 'Web Search Runs',
      'autopilotRunsCount': 'Autopilot Runs',
      'progressInsights': 'Keep going! Your productivity improves with every analysis.',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'privacySecurity': 'Privacy & Security',
      'subscriptionStatus': 'Subscription Status',
      'notifInsightReady': 'New analytics insights are ready.',
      'notifReportGenerated': 'Your report has been generated successfully.',
      'notifSyncComplete': 'Cloud data sync completed.',
      'notifAiSuggestion': 'A smart suggestion is available for your sheet.',
      'today': 'Today',
      'twoFactorAuth': 'Two-factor Authentication',
      'dataEncryption': 'Data Encryption',
      'privacyControls': 'Privacy Controls',
      'appearanceSection': 'Appearance & Experience',
      'workflowSection': 'Workflow & Productivity',
      'aiSection': 'AI Assistant',
      'securitySection': 'Privacy & Security',
      'languageSection': 'Language & Region',
      'compactMode': 'Compact Mode',
      'haptics': 'Haptics',
      'autoSave': 'Auto Save',
      'cloudSync': 'Cloud Sync',
      'offlineCache': 'Offline Cache',
      'smartNotifications': 'Smart Notifications',
      'defaultExportFormat': 'Default Export Format',
      'formulaHints': 'Smart Formula Hints',
      'aiAutofill': 'AI Autofill',
      'highAccuracyMode': 'High Accuracy Mode',
      'experimentalFeatures': 'Experimental Features',
      'secureMode': 'Secure Mode',
      'batterySaver': 'Battery Saver',
      'appLanguage': 'App Language',
      'undo': 'Undo',
      'redo': 'Redo',
      'formulaSupportTip': 'Supported formulas: SUM / AVG / MIN / MAX / cell reference (e.g. =A1)',
      'pasteTable': 'Paste Table',
      'clearSheet': 'Clear Sheet',
      'confirmClearSheet': 'Are you sure you want to clear all cells?',
      'yes': 'Yes',
      'pastedRange': 'Table data pasted successfully',
      'fillDown': 'Fill Down',
      'sortByColumn': 'Sort Column',
      'endRowHint': 'Target end row number',
      'apply': 'Apply',
      'sortState': 'Sort mode',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'columnStats': 'Column Stats',
      'duplicateRow': 'Duplicate Row',
      'insertRowBelow': 'Insert Row Below',
      'insertColumnRight': 'Insert Column Right',
      'goToCell': 'Go to Cell',
      'go': 'Go',
      'arithmeticFormulasTip': 'Supports arithmetic formulas like =A1+B1 and =(A1*2)-3',
      'advancedFormulaTip': 'Advanced formulas: COUNT / MEDIAN over ranges',
      'conditionalFormulaTip': 'Supports IF like =IF(A2>100,"High","Low")',
      'optimizeSheet': 'Optimize Sheet (remove empties)',
      'sheetOptimized': 'Sheet optimized',
      'columnDeepStats': 'Column Deep Stats',
      'sumValue': 'Sum',
      'medianValue': 'Median',
      'varianceValue': 'Variance',
      'stdevValue': 'Std Dev',
      'dispersionFormulaTip': 'Supports STDEV and VAR over ranges',
      'rankingFormulaTip': 'Supports PCTL and RANK for advanced analysis',
      'formulaAssistant': 'Formula Assistant',
      'normalizeColumn': 'Normalize Column (Z-Score)',
      'normalizedCells': 'Normalized cells',
      'outlierDetection': 'Outlier Detection',
      'outlierRows': 'Outlier rows',
      'noOutliers': 'No outliers detected',
      'outlierTip': 'Outlier analytics: IQR + Z-Score normalization',
      'trendInsights': 'Trend Insights',
      'trendSlope': 'Trend Slope',
      'trendIntercept': 'Intercept',
      'samplesUsed': 'Samples Used',
      'nextForecasts': 'Next Forecasts',
      'movingAverage': 'Moving Average',
      'windowSizeHint': 'Window size (e.g. 3)',
      'movingAverageApplied': 'Moving average applied to column',
      'trendTip': 'Trend analysis + auto forecast',
      'goalSeek': 'Goal Seek',
      'goalSeekHint': 'Enter the target Y value',
      'requiredX': 'Required X value',
      'whatIfScenario': 'What-if Scenario',
      'scenarioHint': 'Enter comma-separated X values like 10,20,30',
      'scenarioTip': 'Goal-seek/what-if scenario forecasting',
      'insufficientData': 'Insufficient data for analysis',
      'trimSheet': 'Trim Trailing Empty',
      'sheetTrimmed': 'Sheet trimmed',
      'formulaAudit': 'Formula Audit',
      'formulaAuditClean': 'No formula errors detected',
      'autoExpandPrompt': 'Cell is out of range. Auto-expand the sheet?',
      'count': 'Count',
      'minValue': 'Min Value',
      'maxValue': 'Max Value',
      'avgValue': 'Average',
      'ok': 'OK',
      'findInSheet': 'Find in Sheet',
      'replaceInSheet': 'Replace in Sheet',
      'findHint': 'Enter search text',
      'find': 'Find',
      'replaceWith': 'Replace with',
      'noMatches': 'No matches found',
      'matchesFound': 'Matches found',
      'replacedCount': 'Replaced cells',
      'deleteRow': 'Delete Row',
      'deleteColumn': 'Delete Column',
      'confirmDeleteRow': 'Do you want to delete the selected row?',
      'confirmDeleteColumn': 'Do you want to delete the selected column?',
    },
  };

  String t(String key) => _localizedValues[locale.languageCode]?[key] ?? key;
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}
